# 사용자 정의 (자주 변하는 내용을 최하단으로)

# Base Path
BASE_SRC_PATH="${HOME}/Source_PJT"
BASE_DOCKER_PATH="${HOME}/Docker_PJT"

# Git Personal Info
GIT_USER_EMAIL="dhyeo@autocrypt.io"
GIT_USER_NAME="dhyeo"

# Docker Setting
DOCKER_IMAGE_SUFFIX="yocto"

# PJT Setting
PJT_NAME=test
